"""
A program that draws first and last names using the Python turtle module

Authors: Aj Pabst, David Yuxuan Zhang
Time spent: 5 hours
"""

import turtle

#DAVID YUXUAN ZHANG

def boxing():
    turtle.speed(10)
    turtle.up()
    turtle.setpos(-330,330)
    turtle.color("black","aqua")
    turtle.begin_fill()
    turtle.forward(660)
    turtle.right(90)
    turtle.forward(470)
    turtle.right(90)
    turtle.forward(660)
    turtle.right(90)
    turtle.forward(470)
    turtle.end_fill()

def draw_letter_A():
    turtle.down()
    turtle.forward(35)
    turtle.right(75)
    turtle.forward(110)
    turtle.back(55)
    turtle.setheading(180)
    turtle.forward(63.5)
    turtle.left(75)
    turtle.forward(55)
    turtle.back(110)
    turtle.setheading(0)
    turtle.up()

    
def draw_letter_D():
    turtle.down()
    turtle.forward(75)
    turtle.right(45)
    turtle.forward(20)
    turtle.right(45)
    turtle.forward(90)
    turtle.right(45)
    turtle.forward(20)
    turtle.right(45)
    turtle.forward(75)
    turtle.back(10)
    turtle.right(90)
    turtle.forward(117)
    turtle.setheading(0)
    turtle.up()
    
def draw_letter_G():
    turtle.down()
    turtle.forward(70)
    turtle.back(70)
    turtle.setheading(225)
    turtle.forward(20)
    turtle.setheading(270)
    turtle.forward(75)
    turtle.left(45)
    turtle.forward(20)
    turtle.left(45)
    turtle.forward(65)
    turtle.left(45)
    turtle.forward(20)
    turtle.left(45)
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(55)
    turtle.up()
    turtle.right(90)
    turtle.forward(64.14)
    turtle.setheading(0)
    
def draw_letter_H():
    turtle.down()
    turtle.setheading(270)
    turtle.forward(100)
    turtle.back(50)
    turtle.setheading(0)
    turtle.forward(75)
    turtle.setheading(270)
    turtle.forward(50)
    turtle.back(100)
    turtle.setheading(0)
    turtle.up()
    
def draw_letter_I():
    turtle.down()
    turtle.forward(75)
    turtle.back(37.5)
    turtle.right(90)
    turtle.forward(110)
    turtle.right(90)
    turtle.forward(37.5)
    turtle.back(75)
    turtle.up()
    turtle.setheading(90)
    turtle.forward(110)
    turtle.setheading(0)

def draw_letter_N():
    turtle.down()
    turtle.setheading(-90)
    turtle.forward(100)
    turtle.back(100)
    turtle.setheading(-55)
    turtle.forward(125)
    turtle.setheading(90)
    turtle.forward(100)
    turtle.up()
    turtle.setheading(0)

def draw_letter_O():
    turtle.down()
    turtle.forward(50)
    turtle.left(45)
    turtle.forward(10)
    turtle.left(45)
    turtle.forward(55)
    turtle.left(45)
    turtle.forward(10)
    turtle.left(45)
    turtle.forward(50)
    turtle.left(45)
    turtle.forward(10)
    turtle.left(45)
    turtle.forward(55)
    turtle.left(45)
    turtle.forward(10)
    turtle.up()
    
def draw_letter_P():
    turtle.down()
    turtle.left(90)
    turtle.forward(70)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(45)
    turtle.forward(10)
    turtle.right(45)
    turtle.forward(15)
    turtle.right(45)
    turtle.forward(10)
    turtle.right(45)
    turtle.forward(50)
    turtle.up()
    
def draw_letter_S():
    turtle.down()
    turtle.forward(50)
    turtle.left(45)
    turtle.forward(10)
    turtle.left(45)
    turtle.forward(20)
    turtle.left(45)
    turtle.forward(10)
    turtle.left(45)
    turtle.forward(40)
    turtle.right(45)
    turtle.forward(10)
    turtle.right(45)
    turtle.forward(20)
    turtle.right(45)
    turtle.forward(10)
    turtle.right(45)
    turtle.forward(50)
    turtle.up()

def draw_letter_T():
    turtle.down()
    turtle.left(90)
    turtle.forward(65)
    turtle.left(90)
    turtle.forward(25)
    turtle.left(180)
    turtle.forward(50)
    turtle.up()
    
def draw_letter_C():
    turtle.down()
    turtle.forward(50)
    turtle.back(50)
    turtle.left(90)
    turtle.forward(65)
    turtle.right(90)
    turtle.forward(50)
    turtle.up()
    
def draw_letter_L():
    turtle.down()
    turtle.forward(50)
    turtle.back(50)
    turtle.left(90)
    turtle.forward(65)
    turtle.up()
    
def draw_letter_F():
    turtle.down()
    turtle.setheading(90)
    turtle.forward(65)
    turtle.right(90)
    turtle.forward(50)
    turtle.back(50)
    turtle.right(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(40)
    turtle.up()

def draw_letter_E():
    turtle.down()
    turtle.setheading(90)
    turtle.forward(65)
    turtle.right(90)
    turtle.forward(50)
    turtle.back(50)
    turtle.right(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(40)
    turtle.back(40)
    turtle.right(90)
    turtle.forward(35)
    turtle.left(90)
    turtle.forward(50)
    turtle.up()
    
def draw_letter_U():
    turtle.down()
    turtle.right(90)
    turtle.forward(90)
    turtle.left(45)
    turtle.forward(20)
    turtle.left(45)
    turtle.forward(60)
    turtle.left(45)
    turtle.forward(20)
    turtle.left(45)
    turtle.forward(90)
    turtle.up()
    turtle.setheading(0)
    
def draw_letter_V():
    turtle.down()
    turtle.setheading(290)
    turtle.forward(120)
    turtle.setheading(70)
    turtle.forward(120)
    turtle.up()
    turtle.setheading(0)
    
def draw_letter_X():
    turtle.down()
    turtle.setheading(-45)
    turtle.forward(140)
    turtle.back(70)
    turtle.setheading(45)
    turtle.forward(70)
    turtle.back(140)
    turtle.up()
    turtle.forward(140)
    turtle.setheading(0)
    
def draw_letter_Y():
    turtle.down()
    turtle.setheading(-45)
    turtle.forward(55)
    turtle.setheading(-90)
    turtle.forward(60)
    turtle.back(60)
    turtle.setheading(45)
    turtle.forward(55)
    turtle.up()
    turtle.setheading(0)

def draw_letter_Z():
    turtle.down()
    turtle.forward(75)
    turtle.setheading(235)
    turtle.forward(120)
    turtle.setheading(0)
    turtle.forward(75)
    turtle.up()
    turtle.setheading(90)
    turtle.forward(98.3)
    turtle.setheading(0)
 
#I used turtle.setpos() to relocate the turtle.
def draw_name():
    turtle.shape("turtle")
    boxing()
    turtle.speed(5)
    turtle.up()
    turtle.setpos(-250,300)
    turtle.setheading(0)
    turtle.pensize(10)
    
    turtle.pencolor('#8A2BE2')
    draw_letter_D()
    turtle.forward(130)
    draw_letter_A()
    turtle.forward(60)
    draw_letter_V()
    turtle.forward(20)
    draw_letter_I()
    turtle.forward(20)
    draw_letter_D()
    
    turtle.pencolor('#FFF8DC')
    turtle.setpos(-300,150)
    draw_letter_Y()
    turtle.forward(20)
    draw_letter_U()
    turtle.forward(20)
    draw_letter_X()
    turtle.forward(20)
    draw_letter_U()
    turtle.forward(50)
    draw_letter_A()
    turtle.forward(80)
    draw_letter_N()
    
    turtle.pencolor('#00FF00')
    turtle.setpos(-250,0)
    draw_letter_Z()
    turtle.forward(20)
    draw_letter_H()
    turtle.forward(45)
    draw_letter_A()
    turtle.forward(80)
    draw_letter_N()
    turtle.forward(40)
    draw_letter_G()

    turtle.setpos(-300,-250)
    turtle.setheading(0)
    draw_letter_O()
    turtle.setpos(-220,-250)
    turtle.setheading(0)
    draw_letter_P()
    turtle.setpos(-150,-250)
    turtle.setheading(0)
    draw_letter_S()
    turtle.setpos(-40,-250)
    turtle.setheading(0)
    draw_letter_T()
    turtle.setpos(10,-250)
    turtle.setheading(0)
    draw_letter_C()
    turtle.setpos(100,-250)
    turtle.setheading(0)
    draw_letter_L()
    turtle.setpos(180,-250)
    turtle.setheading(0)
    draw_letter_F()
    turtle.setpos(250,-250)
    turtle.setheading(0)
    draw_letter_E()
    
    turtle.done()
    
def main():
    draw_name()

if __name__ == '__main__':
    main()
    